version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
executors:
  python-executor:
    docker:
      - image: cimg/python:3.10.13
    working_directory: ~/repo
jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
            - v1-pip-cache-
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install 'setuptools<58.0.0'
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Download Selenium Standalone Server
          command: |
            mkdir -p selenium
            wget -O selenium/selenium-server-standalone.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-results
          destination: test-results
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - heroku/deploy-via-git:
          app-name: YOUR_HEROKU_APP_NAME
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          context: heroku
